/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iel.view;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class Principal extends javax.swing.JFrame {

    public boolean qmJoga = true;
    public String[] arrayJogo = new String[9];
    public int tamTab = 3;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJogador1 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        lblPonto1 = new javax.swing.JLabel();
        lblPonto2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnZeroZero = new javax.swing.JButton();
        btnZeroUm = new javax.swing.JButton();
        btnZeroDois = new javax.swing.JButton();
        btnUmZero = new javax.swing.JButton();
        btnUmUm = new javax.swing.JButton();
        btnUmDois = new javax.swing.JButton();
        btnDoisZero = new javax.swing.JButton();
        btnDoisUm = new javax.swing.JButton();
        btnDoisDois = new javax.swing.JButton();
        lblAtaul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJogador1.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblJogador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJogador1.setText("Jogador 1");

        lblJogador2.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblJogador2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJogador2.setText("Jogador 2");

        lblPonto1.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        lblPonto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto1.setText("0");

        lblPonto2.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        lblPonto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto2.setText("0");

        btnZeroZero.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroZeroActionPerformed(evt);
            }
        });

        btnZeroUm.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnZeroUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroUmActionPerformed(evt);
            }
        });

        btnZeroDois.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnZeroDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroDoisActionPerformed(evt);
            }
        });

        btnUmZero.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnUmZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmZeroActionPerformed(evt);
            }
        });

        btnUmUm.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnUmUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmUmActionPerformed(evt);
            }
        });

        btnUmDois.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnUmDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmDoisActionPerformed(evt);
            }
        });

        btnDoisZero.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnDoisZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisZeroActionPerformed(evt);
            }
        });

        btnDoisUm.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnDoisUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisUmActionPerformed(evt);
            }
        });

        btnDoisDois.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        btnDoisDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisDoisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZeroUm, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZeroDois, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUmZero, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUmUm, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUmDois, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDoisZero, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoisUm, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoisDois, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnZeroZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZeroUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZeroDois, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUmZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUmUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUmDois, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDoisZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoisUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoisDois, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAtaul.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 25)); // NOI18N
        lblAtaul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtaul.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAtaul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(lblPonto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPonto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAtaul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUmDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmDoisActionPerformed
        viraBotao(btnUmDois, 5);
    }//GEN-LAST:event_btnUmDoisActionPerformed

    private void btnZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroZeroActionPerformed
        viraBotao(btnZeroZero, 0);
    }//GEN-LAST:event_btnZeroZeroActionPerformed

    private void btnZeroUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroUmActionPerformed
        viraBotao(btnZeroUm, 1);
    }//GEN-LAST:event_btnZeroUmActionPerformed

    private void btnZeroDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroDoisActionPerformed
        viraBotao(btnZeroDois, 2);
    }//GEN-LAST:event_btnZeroDoisActionPerformed

    private void btnUmZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmZeroActionPerformed
        viraBotao(btnUmZero, 3);
    }//GEN-LAST:event_btnUmZeroActionPerformed

    private void btnUmUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmUmActionPerformed
        viraBotao(btnUmUm, 4);
    }//GEN-LAST:event_btnUmUmActionPerformed

    private void btnDoisZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisZeroActionPerformed
        viraBotao(btnDoisZero, 6);
    }//GEN-LAST:event_btnDoisZeroActionPerformed

    private void btnDoisUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisUmActionPerformed
        viraBotao(btnDoisUm, 7);
    }//GEN-LAST:event_btnDoisUmActionPerformed

    private void btnDoisDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisDoisActionPerformed
        viraBotao(btnDoisDois, 8);
    }//GEN-LAST:event_btnDoisDoisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void viraBotao(JButton botao, int valorBotao) {
        if (botao.getText() == "" && botao.getText() != "X" && botao.getText() != "O") {
            String valorJogador;
            if (qmJoga) {
                valorJogador = "X";
                lblAtaul.setText("O");
            } else {
                valorJogador = "O";
                lblAtaul.setText("X");
            }
            botao.setText(valorJogador);
            arrayJogo[valorBotao] = valorJogador;
            if (verificaVitoria(valorJogador)) {
                String jogador;
                if (valorJogador == "X") {
                    jogador = lblJogador1.getText();
                } else {
                    jogador = lblJogador2.getText();
                }
                JOptionPane.showMessageDialog(this, "Parabéns, o jogador " + jogador + " venceu o jogo", "VENCEDOR", JOptionPane.OK_OPTION);
            }
            qmJoga = !qmJoga;
        }
    }
    
    public boolean verificaVelha(){
        return true;
    }

    public boolean verificaVitoria(String valorJogador) {
        for (int i = 0; i < tamTab; i++) {
            if (verificaHorizontal(valorJogador, tamTab*i)) {
                return true;
            }
        }
        for (int i = 0; i < tamTab; i++) {
            if (verificaVertical(valorJogador, tamTab+i)) {
                return true;
            }
        }
        if (verificaDiagonal1(valorJogador)) {
            return true;
        }
        if (verificaDiagonal2(valorJogador)) {
            return true;
        }
        return false;
    }

    public boolean verificaHorizontal(String valorJogador, int valor) {
        for (int i = valor; i < valor+tamTab; i++) {
            if (arrayJogo[i] != valorJogador) {
                return false;
            }
        }
        return true;
    }

    public boolean verificaVertical(String valorJogador, int valor) {
        for (int i = valor; i < Math.pow(tamTab, 2); i += tamTab) {
            if (arrayJogo[i] != valorJogador) {
                return false;
            }
        }
        return true;
    }

    public boolean verificaDiagonal1(String valorJogador) {
        for (int i = 0; i < Math.pow(tamTab, 2); i += tamTab + 1) {
            if (arrayJogo[i] != valorJogador) {
                return false;
            }
        }
        return true;
    }

    public boolean verificaDiagonal2(String valorJogador) {
        for (int i = 0; i < Math.pow(tamTab, 2); i += tamTab - 1) {
            if (arrayJogo[i] != valorJogador) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoisDois;
    private javax.swing.JButton btnDoisUm;
    private javax.swing.JButton btnDoisZero;
    private javax.swing.JButton btnUmDois;
    private javax.swing.JButton btnUmUm;
    private javax.swing.JButton btnUmZero;
    private javax.swing.JButton btnZeroDois;
    private javax.swing.JButton btnZeroUm;
    private javax.swing.JButton btnZeroZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtaul;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblPonto1;
    private javax.swing.JLabel lblPonto2;
    // End of variables declaration//GEN-END:variables
}
